### ISSUE TITLE
Is it possible to retrain on custom Table data

### ISSUE THREAD

**Issue by Sharathmk99** [rinkstiekema/PDF-Table-Structure-Recognition-using-deep-learning#10]
Hi.
Thank you for the great work and open sourcing the same. I was wondering is it possible to train from scratch and also retrain on custom Table data? 
Thank you.

**Comment by rinkstiekema** [comment]
Absolutely, you can take any of the models and retrain them using train.py in:
./pipeline/pix2pixHD/train.py and ./pipeline/segmentation/train.py

You could also train any other type of model if you want.

**Comment by Sharathmk99** [comment]
@rinkstiekema Can you share sample training data required to train the model? How should we annotate the table?

**Comment by rinkstiekema** [comment]
You can find an example dataset in this google drive:
https://drive.google.com/drive/u/0/folders/1dgKISbhBNfR8XXnIxUD_sIhwYNurKHbb
