### ISSUE TITLE
can you provide a pre-training model 

### ISSUE THREAD

**Issue by SolinTao** [rinkstiekema/PDF-Table-Structure-Recognition-using-deep-learning#2]
hi, can you provide a pre-training model ?

**Comment by rinkstiekema** [comment]
I will try to upload one next week!

**Comment by cooleel** [comment]
Hi, thanks a lot for this project, it seems very useful.
Any updates on uploading a pre-trained model?

**Comment by rinkstiekema** [comment]
It took me quite a while, sorry for that, but I finally uploaded the models. You can find them in the models folder.
