### ISSUE TITLE
Where to download pdffigures2.jar?

### ISSUE THREAD

**Issue by Gingersna** [rinkstiekema/PDF-Table-Structure-Recognition-using-deep-learning#6]
the .jar file that I downloaded at websit(https://repo.spring.io/plugins-release/org/allenai/pdffigures2_2.11/0.0.6/)
report `no main manifest attribute, in pdffigures2.jar`

**Comment by rinkstiekema** [comment]
This repo should work:
https://github.com/allenai/pdffigures2
