### ISSUE TITLE
problem about output

### ISSUE THREAD

**Issue by cocococo-s** [rinkstiekema/PDF-Table-Structure-Recognition-using-deep-learning#9]
Hello after I run it with your code, There is no result output in the csv_pred_pix2pixHD directory
the command is
`python batch.py --dataroot data/ --model pix2pixHD --checkpoint_dir ../models/pix2pix-model/`
and my directory structure is
--pipeline
----data
------csv_pred_pix2pixHD
------json
------outlines_pix2pixHD
------pdf
------png
----batch.py
I only put a picture in the png directory (15664-Table1-1.png)
and the final result is an image was generated under the outlines_pix2pixHD directory (15664-Table1-1.png)
other directories are empty at the beginning and last, So I want to ask if this is correct ? Why is there no output from csv_pred_pix2pixHD directory? Is the file in outlines_pix2pixHD the result of your table structure recognition?

**Comment by rinkstiekema** [comment]
Did you have the PDF in the PDF folder?

**Comment by cocococo-s** [comment]
Thank you for your reply, and later I found the reason after reading the code！
i just put a picture in the png directory Then use your code to predict its structure，Does the output of outlines_pix2pixHD directory represent the pic's predict structure?

**Comment by rinkstiekema** [comment]
Correct, the output represents the predicted structure by predicting where the tables lines are, as the lines separate columns and rows. It will also try to predict the "latent" lines that have been omitted by the creator of the table.
